spring.application.name=e-journal
spring.datasource.url=jdbc:postgresql://localhost:5432/ejournal
spring.datasource.username=ejournal_usr
spring.datasource.password=ejournal_pwd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
app.jwtSecret=YourSuperSecretKeyThatShouldBeAtLeast64BytesLongForHS512Algorithm
app.jwtExpirationInMs=86400000
# Grant all roles to unauthenticated requests from 127.0.0.1 — set to false for staging/production
app.security.allow-localhost=true