spring.application.name=e-journal
spring.datasource.url=jdbc:postgresql://localhost:5432/e-journal
spring.datasource.username=programmers
spring.datasource.password=KWxu6SyPmPV62UWTjvtbXJOXRAhdxZPENSmSUO02TqokpJem9qPF9X5iCb2JR4cm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true